### ISSUE TITLE
[Sponge]: Plugin 'foxmisc' seems to be missing a valid mcmod.info metadata file.

### ISSUE THREAD

**Issue by ziceptor** [FoxDenStudio/FoxMisc#2]
http://pastebin.com/xM4mC2qT

**Comment by ghost** [comment]
Hello,

@ziceptor just so you know, FoxMisc is not currently being worked on, in favor of working on FoxEdit, and FoxGuard/FoxCore.

Due to that, FoxMisc has not been updated in quite some time, and has really been used more for testing then anything else.

Until such a time that we start working on the plugin again, there will be numerous errors and mistakes when run on a server.

Thanks for your interest though!

Joshua & Mike

**Comment by ziceptor** [comment]
Strange approach. Even if the work is suspended, why close the issue? It's a "pill for memory"... no more. My job is to inform the developer about the problem. Do as you will comfortably.

**Comment by ghost** [comment]
@ziceptor sorry about that, I copy and pasted the response from an older one, and modified it, but didn't really read it.

**Comment by gravityfox** [comment]
So basically this issue was ALSO fixed, when i updated the build scripts to match the ones used for FoxGuard and the like, but like the last issue, Travis isn't building for some reason, and I need to take a look at it. I might even do that right now.
